#compdef {{APP_NAME}}
# Zsh completion for {{APP_NAME}}
# Generated by TimeWarp.Nuru.Completion

_{{APP_NAME}}() {
    local -a commands
    commands=(
        {{COMMANDS}}
    )

    _arguments -C \
{{ARGUMENTS_SPEC}}
      '1: :->commands' \
      '*::arg:->args'

    case $state in
        commands)
            _describe 'command' commands
            ;;
        args)
            _files
            ;;
    esac
}

_{{APP_NAME}} "$@"
