#!/usr/bin/dotnet --

// Shell Completion Endpoint Protocol Tests
// Tests the __complete callback and completion routes generated by EnableCompletion()
// Reference: samples/15-completion/manual-testing.md

#if !JARIBU_MULTI
return await RunAllTests();
#endif

namespace TimeWarp.Nuru.Tests.Completion.EndpointProtocol
{

[TestTag("Completion")]
public class CompletionEndpointProtocolTests
{
  [ModuleInitializer]
  internal static void Register() => RegisterTests<CompletionEndpointProtocolTests>();

  // ==========================================================================
  // __complete Callback Tests
  // ==========================================================================

  public static async Task Complete_should_return_commands_at_position_1()
  {
    // Arrange
    using TestTerminal terminal = new();

    NuruApp app = NuruApp.CreateBuilder([])
      .UseTerminal(terminal)
      .Map("deploy {env}").WithHandler((string env) => 0).AsCommand().Done()
      .Map("list-environments").WithHandler(() => { }).AsQuery().Done()
      .Map("status").WithHandler(() => { }).AsQuery().Done()
      .EnableCompletion()
      .Build();

    // Act
    int exitCode = await app.RunAsync(["__complete", "1", "app"]);

    // Assert
    exitCode.ShouldBe(0);
    terminal.OutputContains("deploy").ShouldBeTrue();
    terminal.OutputContains("list-environments").ShouldBeTrue();
    terminal.OutputContains("status").ShouldBeTrue();
    terminal.OutputContains(":4").ShouldBeTrue(); // NoFileComp directive
  }

  public static async Task Complete_should_filter_commands_by_prefix()
  {
    // Arrange
    using TestTerminal terminal = new();

    NuruApp app = NuruApp.CreateBuilder([])
      .UseTerminal(terminal)
      .Map("deploy {env}").WithHandler((string env) => 0).AsCommand().Done()
      .Map("delete {item}").WithHandler((string item) => 0).AsCommand().Done()
      .Map("status").WithHandler(() => { }).AsQuery().Done()
      .EnableCompletion()
      .Build();

    // Act
    int exitCode = await app.RunAsync(["__complete", "1", "app", "dep"]);

    // Assert
    exitCode.ShouldBe(0);
    terminal.OutputContains("deploy").ShouldBeTrue();
    terminal.OutputContains("delete").ShouldBeFalse(); // Filtered out - doesn't start with "dep"
    terminal.OutputContains("status").ShouldBeFalse(); // Filtered out
  }

  public static async Task Complete_should_use_custom_completion_source_for_parameter()
  {
    // Arrange
    using TestTerminal terminal = new();

    NuruApp app = NuruApp.CreateBuilder([])
      .UseTerminal(terminal)
      .Map("deploy {env}").WithHandler((string env) => 0).AsCommand().Done()
      .EnableCompletion(configure: registry =>
      {
        registry.RegisterForParameter("env", new TestEnvironmentSource());
      })
      .Build();

    // Act
    int exitCode = await app.RunAsync(["__complete", "2", "app", "deploy"]);

    // Assert
    exitCode.ShouldBe(0);
    terminal.OutputContains("production").ShouldBeTrue();
    terminal.OutputContains("staging").ShouldBeTrue();
    terminal.OutputContains("development").ShouldBeTrue();
  }

  public static async Task Complete_should_include_help_option()
  {
    // Arrange
    using TestTerminal terminal = new();

    NuruApp app = NuruApp.CreateBuilder([])
      .UseTerminal(terminal)
      .Map("status").WithHandler(() => { }).AsQuery().Done()
      .EnableCompletion()
      .Build();

    // Act
    int exitCode = await app.RunAsync(["__complete", "1", "app"]);

    // Assert
    exitCode.ShouldBe(0);
    terminal.OutputContains("--help").ShouldBeTrue();
  }

  public static async Task Complete_should_handle_empty_input()
  {
    // Arrange
    using TestTerminal terminal = new();

    NuruApp app = NuruApp.CreateBuilder([])
      .UseTerminal(terminal)
      .Map("status").WithHandler(() => { }).AsQuery().Done()
      .EnableCompletion()
      .Build();

    // Act - Cursor at position 1 with just app name
    int exitCode = await app.RunAsync(["__complete", "1", "app"]);

    // Assert
    exitCode.ShouldBe(0);
    terminal.OutputContains(":4").ShouldBeTrue(); // Should still have directive
  }

  public static async Task Complete_should_output_directive_code()
  {
    // Arrange
    using TestTerminal terminal = new();

    NuruApp app = NuruApp.CreateBuilder([])
      .UseTerminal(terminal)
      .Map("status").WithHandler(() => { }).AsQuery().Done()
      .EnableCompletion()
      .Build();

    // Act
    int exitCode = await app.RunAsync(["__complete", "1", "app"]);

    // Assert
    exitCode.ShouldBe(0);
    // Output should contain directive line (":N" where N is directive code)
    // :4 = NoFileComp directive
    terminal.OutputContains(":4").ShouldBeTrue();
  }

  // ==========================================================================
  // --generate-completion Tests
  // ==========================================================================

  public static async Task GenerateCompletion_bash_should_return_bash_script()
  {
    // Arrange
    using TestTerminal terminal = new();

    NuruApp app = NuruApp.CreateBuilder([])
      .UseTerminal(terminal)
      .Map("status").WithHandler(() => { }).AsQuery().Done()
      .EnableCompletion()
      .Build();

    // Act
    int exitCode = await app.RunAsync(["--generate-completion", "bash"]);

    // Assert
    exitCode.ShouldBe(0);
    terminal.OutputContains("_completions()").ShouldBeTrue(); // Bash function pattern
    terminal.OutputContains("__complete").ShouldBeTrue(); // Callback invocation
  }

  public static async Task GenerateCompletion_zsh_should_return_zsh_script()
  {
    // Arrange
    using TestTerminal terminal = new();

    NuruApp app = NuruApp.CreateBuilder([])
      .UseTerminal(terminal)
      .Map("status").WithHandler(() => { }).AsQuery().Done()
      .EnableCompletion()
      .Build();

    // Act
    int exitCode = await app.RunAsync(["--generate-completion", "zsh"]);

    // Assert
    exitCode.ShouldBe(0);
    terminal.OutputContains("#compdef").ShouldBeTrue(); // Zsh compdef directive
    terminal.OutputContains("__complete").ShouldBeTrue();
  }

  public static async Task GenerateCompletion_fish_should_return_fish_script()
  {
    // Arrange
    using TestTerminal terminal = new();

    NuruApp app = NuruApp.CreateBuilder([])
      .UseTerminal(terminal)
      .Map("status").WithHandler(() => { }).AsQuery().Done()
      .EnableCompletion()
      .Build();

    // Act
    int exitCode = await app.RunAsync(["--generate-completion", "fish"]);

    // Assert
    exitCode.ShouldBe(0);
    terminal.OutputContains("function __fish_").ShouldBeTrue(); // Fish function pattern
    terminal.OutputContains("__complete").ShouldBeTrue();
  }

  public static async Task GenerateCompletion_pwsh_should_return_powershell_script()
  {
    // Arrange
    using TestTerminal terminal = new();

    NuruApp app = NuruApp.CreateBuilder([])
      .UseTerminal(terminal)
      .Map("status").WithHandler(() => { }).AsQuery().Done()
      .EnableCompletion()
      .Build();

    // Act
    int exitCode = await app.RunAsync(["--generate-completion", "pwsh"]);

    // Assert
    exitCode.ShouldBe(0);
    terminal.OutputContains("Register-ArgumentCompleter").ShouldBeTrue(); // PowerShell pattern
    terminal.OutputContains("__complete").ShouldBeTrue();
  }

  public static async Task GenerateCompletion_should_reject_unknown_shell()
  {
    // Arrange
    using TestTerminal terminal = new();

    NuruApp app = NuruApp.CreateBuilder([])
      .UseTerminal(terminal)
      .Map("status").WithHandler(() => { }).AsQuery().Done()
      .EnableCompletion()
      .Build();

    // Act & Assert - Should throw for unknown shell
    try
    {
      await app.RunAsync(["--generate-completion", "unknown"]);
      throw new ShouldAssertException("Expected ArgumentException but none was thrown");
    }
    catch (ArgumentException ex)
    {
      ex.Message.ShouldContain("Unknown shell");
    }
  }

  // ==========================================================================
  // --install-completion Tests
  // ==========================================================================

  public static async Task InstallCompletion_dryrun_should_show_paths()
  {
    // Arrange
    using TestTerminal terminal = new();

    NuruApp app = NuruApp.CreateBuilder([])
      .UseTerminal(terminal)
      .Map("status").WithHandler(() => { }).AsQuery().Done()
      .EnableCompletion()
      .Build();

    // Act
    int exitCode = await app.RunAsync(["--install-completion", "--dry-run"]);

    // Assert
    exitCode.ShouldBe(0);
    terminal.OutputContains("Dry run").ShouldBeTrue();
    terminal.OutputContains("Would write to").ShouldBeTrue();
  }

  public static async Task InstallCompletion_dryrun_bash_should_show_bash_path()
  {
    // Arrange
    using TestTerminal terminal = new();

    NuruApp app = NuruApp.CreateBuilder([])
      .UseTerminal(terminal)
      .Map("status").WithHandler(() => { }).AsQuery().Done()
      .EnableCompletion()
      .Build();

    // Act
    int exitCode = await app.RunAsync(["--install-completion", "--dry-run", "bash"]);

    // Assert
    exitCode.ShouldBe(0);
    terminal.OutputContains("Bash").ShouldBeTrue();
    terminal.OutputContains("bash-completion").ShouldBeTrue();
  }
}

// ==========================================================================
// Test Helpers
// ==========================================================================

/// <summary>
/// Test completion source that returns environment names.
/// </summary>
sealed class TestEnvironmentSource : ICompletionSource
{
  public IEnumerable<CompletionCandidate> GetCompletions(CompletionContext context)
  {
    string[] environments = ["production", "staging", "development"];
    return environments.Select(e => new CompletionCandidate(
      Value: e,
      Description: $"{e} environment",
      Type: CompletionType.Parameter
    ));
  }
}

} // namespace TimeWarp.Nuru.Tests.Completion.EndpointProtocol
