namespace TimeWarp.Nuru;

/// <summary>
/// Code generation methods for generating typed invoker methods, lookup dictionaries,
/// and module initializer registration code.
/// </summary>
public partial class NuruInvokerGenerator
{
  private static string GenerateInvokersClass(List<DelegateSignature> signatures)
  {
    System.Text.StringBuilder sb = new();

    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("// Generated by TimeWarp.Nuru.Analyzers - NuruInvokerGenerator");
    sb.AppendLine("// DO NOT EDIT");
    sb.AppendLine();
    sb.AppendLine("#nullable enable");
    sb.AppendLine();
    sb.AppendLine("namespace TimeWarp.Nuru.Generated;");
    sb.AppendLine();
    sb.AppendLine("/// <summary>");
    sb.AppendLine("/// Generated typed invoker methods for route handlers.");
    sb.AppendLine("/// These methods enable reflection-free delegate invocation for AOT compatibility.");
    sb.AppendLine("/// </summary>");
    sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"TimeWarp.Nuru.Analyzers\", \"1.0.0\")]");
    sb.AppendLine("internal static class GeneratedRouteInvokers");
    sb.AppendLine("{");

    foreach (DelegateSignature signature in signatures)
    {
      GenerateInvokerMethod(sb, signature);
      sb.AppendLine();
    }

    // Generate the lookup dictionary
    GenerateLookupDictionary(sb, signatures);

    sb.AppendLine("}");
    sb.AppendLine();

    // Generate the module initializer to register invokers
    GenerateModuleInitializer(sb);

    return sb.ToString();
  }

  private static void GenerateModuleInitializer(System.Text.StringBuilder sb)
  {
    sb.AppendLine("/// <summary>");
    sb.AppendLine("/// Module initializer that registers generated invokers with the InvokerRegistry.");
    sb.AppendLine("/// </summary>");
    sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"TimeWarp.Nuru.Analyzers\", \"1.0.0\")]");
    sb.AppendLine("internal static class GeneratedInvokerRegistration");
    sb.AppendLine("{");
    sb.AppendLine("  [global::System.Runtime.CompilerServices.ModuleInitializer]");
    sb.AppendLine("  internal static void Register()");
    sb.AppendLine("  {");
    sb.AppendLine("    global::TimeWarp.Nuru.InvokerRegistry.RegisterSyncBatch(GeneratedRouteInvokers.SyncInvokers);");
    sb.AppendLine("    global::TimeWarp.Nuru.InvokerRegistry.RegisterAsyncInvokerBatch(GeneratedRouteInvokers.AsyncInvokers);");
    sb.AppendLine("  }");
    sb.AppendLine("}");
  }

  private static void GenerateInvokerMethod(System.Text.StringBuilder sb, DelegateSignature signature)
  {
    string methodName = GetInvokerMethodName(signature);
    bool isAsync = signature.IsAsync;

    // Generate XML documentation
    sb.AppendLine("  /// <summary>");
    sb.Append(CultureInfo.InvariantCulture, $"  /// Invoker for signature: {signature.UniqueIdentifier}");
    sb.AppendLine();
    sb.AppendLine("  /// </summary>");

    // Generate method signature
    if (isAsync)
    {
      sb.Append(CultureInfo.InvariantCulture, $"  public static async global::System.Threading.Tasks.Task<object?> {methodName}(");
      sb.AppendLine();
      sb.AppendLine("    global::System.Delegate handler,");
      sb.AppendLine("    object?[] args)");
    }
    else
    {
      sb.Append(CultureInfo.InvariantCulture, $"  public static object? {methodName}(");
      sb.AppendLine();
      sb.AppendLine("    global::System.Delegate handler,");
      sb.AppendLine("    object?[] args)");
    }

    sb.AppendLine("  {");

    // Generate the cast and invocation
    string delegateType = GetDelegateTypeName(signature);
    string castExpression = string.Create(CultureInfo.InvariantCulture, $"(({delegateType})handler)");
    string argsExpression = GetArgumentsExpression(signature);

    if (signature.ReturnType.IsVoid)
    {
      // Action delegate - void return
      sb.Append(CultureInfo.InvariantCulture, $"    {castExpression}({argsExpression});");
      sb.AppendLine();
      sb.AppendLine("    return null;");
    }
    else if (isAsync)
    {
      // Async delegate - Task or Task<T>
      if (signature.ReturnType.TaskResultType is not null)
      {
        // Task<T> - return the result
        sb.Append(CultureInfo.InvariantCulture, $"    return await {castExpression}({argsExpression});");
        sb.AppendLine();
      }
      else
      {
        // Task - no result
        sb.Append(CultureInfo.InvariantCulture, $"    await {castExpression}({argsExpression});");
        sb.AppendLine();
        sb.AppendLine("    return null;");
      }
    }
    else
    {
      // Func delegate - returns a value
      sb.Append(CultureInfo.InvariantCulture, $"    return {castExpression}({argsExpression});");
      sb.AppendLine();
    }

    sb.AppendLine("  }");
  }

  private static void GenerateLookupDictionary(System.Text.StringBuilder sb, List<DelegateSignature> signatures)
  {
    sb.AppendLine("  /// <summary>");
    sb.AppendLine("  /// Lookup dictionary for invokers by signature identifier.");
    sb.AppendLine("  /// </summary>");
    sb.AppendLine("  public static global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Func<global::System.Delegate, object?[], object?>> SyncInvokers { get; } =");
    sb.AppendLine("    new global::System.Collections.Generic.Dictionary<string, global::System.Func<global::System.Delegate, object?[], object?>>");
    sb.AppendLine("    {");

    foreach (DelegateSignature signature in signatures.Where(s => !s.IsAsync))
    {
      string methodName = GetInvokerMethodName(signature);
      sb.Append(CultureInfo.InvariantCulture, $"      [\"{signature.UniqueIdentifier}\"] = {methodName},");
      sb.AppendLine();
    }

    sb.AppendLine("    };");
    sb.AppendLine();

    sb.AppendLine("  /// <summary>");
    sb.AppendLine("  /// Lookup dictionary for async invokers by signature identifier.");
    sb.AppendLine("  /// </summary>");
    sb.AppendLine("  public static global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Func<global::System.Delegate, object?[], global::System.Threading.Tasks.Task<object?>>> AsyncInvokers { get; } =");
    sb.AppendLine("    new global::System.Collections.Generic.Dictionary<string, global::System.Func<global::System.Delegate, object?[], global::System.Threading.Tasks.Task<object?>>>");
    sb.AppendLine("    {");

    foreach (DelegateSignature signature in signatures.Where(s => s.IsAsync))
    {
      string methodName = GetInvokerMethodName(signature);
      sb.Append(CultureInfo.InvariantCulture, $"      [\"{signature.UniqueIdentifier}\"] = {methodName},");
      sb.AppendLine();
    }

    sb.AppendLine("    };");
  }

  private static string GetInvokerMethodName(DelegateSignature signature)
  {
    string prefix = signature.IsAsync ? "InvokeAsync" : "Invoke";
    return string.Create(CultureInfo.InvariantCulture, $"{prefix}_{signature.UniqueIdentifier}");
  }

  private static string GetDelegateTypeName(DelegateSignature signature)
  {
    if (signature.Parameters.Length == 0)
    {
      // No parameters
      if (signature.ReturnType.IsVoid)
        return "global::System.Action";

      return string.Create(CultureInfo.InvariantCulture, $"global::System.Func<{signature.ReturnType.FullName}>");
    }

    // Build type parameter list
    System.Text.StringBuilder typeParams = new();
    foreach (DelegateParameterInfo param in signature.Parameters)
    {
      if (typeParams.Length > 0)
        typeParams.Append(", ");

      typeParams.Append(param.Type.FullName);
      // Append ? for nullable reference types only
      // Nullable value types (int?, etc.) already have ? in their FullName from ToDisplayString
      if (param.IsNullable && !param.Type.FullName.EndsWith('?'))
        typeParams.Append('?');
    }

    if (signature.ReturnType.IsVoid)
    {
      return string.Create(CultureInfo.InvariantCulture, $"global::System.Action<{typeParams}>");
    }

    return string.Create(CultureInfo.InvariantCulture, $"global::System.Func<{typeParams}, {signature.ReturnType.FullName}>");
  }

  private static string GetArgumentsExpression(DelegateSignature signature)
  {
    if (signature.Parameters.Length == 0)
      return string.Empty;

    System.Text.StringBuilder args = new();
    for (int i = 0; i < signature.Parameters.Length; i++)
    {
      if (args.Length > 0)
        args.Append(", ");

      DelegateParameterInfo param = signature.Parameters[i];

      // Cast args[i] to the correct type
      // For value types, we need to unbox; for reference types, we cast
      if (param.IsNullable)
      {
        // For nullable types, cast to the nullable type (add ? if not already present)
        string castType = param.Type.FullName.EndsWith('?')
          ? param.Type.FullName
          : param.Type.FullName + "?";
        args.Append(CultureInfo.InvariantCulture, $"({castType})args[{i}]");
      }
      else
      {
        args.Append(CultureInfo.InvariantCulture, $"({param.Type.FullName})args[{i}]!");
      }
    }

    return args.ToString();
  }
}
