namespace TimeWarp.Nuru;

/// <summary>
/// V2 source generator stub - only runs when UseNewGen=true.
/// Emits a marker type to verify the generator ran.
/// </summary>
/// <remarks>
/// This is the entry point for the new compile-time endpoint generation system.
/// When UseNewGen=true:
/// <list type="bullet">
///   <item><description>V1 generators (NuruAttributedRouteGenerator, NuruDelegateCommandGenerator, NuruInvokerGenerator) are skipped</description></item>
///   <item><description>This V2 generator runs and emits compile-time generated code</description></item>
/// </list>
/// Currently this is a stub that emits a marker type to prove the toggle works.
/// </remarks>
[Generator]
public class NuruV2Generator : IIncrementalGenerator
{
  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    IncrementalValueProvider<bool> useNewGen = GeneratorHelpers.GetUseNewGenProvider(context);

    context.RegisterSourceOutput(useNewGen, static (ctx, enabled) =>
    {
      if (!enabled)
        return;

      const string source = """
        // <auto-generated/>
        // This file was generated by NuruV2Generator when UseNewGen=true

        namespace TimeWarp.Nuru.V2.Generated;

        /// <summary>
        /// Marker type indicating V2 generator ran successfully.
        /// This type is only generated when the UseNewGen MSBuild property is set to true.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("TimeWarp.Nuru.Analyzers.V2", "1.0.0")]
        internal static class NuruV2GeneratorMarker
        {
          /// <summary>
          /// The version of the V2 generator.
          /// </summary>
          public const string Version = "2.0.0-stub";

          /// <summary>
          /// Indicates this is V2 generated code.
          /// </summary>
          public const bool IsV2 = true;
        }
        """;

      ctx.AddSource("NuruV2GeneratorMarker.g.cs", source);
    });
  }
}
