# Bash completion for {{APP_NAME}}
# Generated by TimeWarp.Nuru.Completion

_{{APP_NAME}}_completions()
{
    local cur prev words cword
    _init_completion || return

    # Available commands
    local commands="{{COMMANDS}}"

    # Available options
    local options="{{OPTIONS}}"

    # If we're completing the first argument, suggest commands
    if [[ $cword -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "$commands" -- "$cur") )
        return 0
    fi

    # If current word starts with -, suggest options
    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "$options" -- "$cur") )
        return 0
    fi

    # Default: file completion
    _filedir
    return 0
}

complete -F _{{APP_NAME}}_completions {{APP_NAME}}
