# PowerShell completion for {{APP_NAME}}
# Generated by TimeWarp.Nuru.Completion

Register-ArgumentCompleter -Native -CommandName {{APP_NAME}} -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $completions = @(
{{COMPLETIONS}}
    )

    $completions | Where-Object { $_.CompletionText -like "$wordToComplete*" } |
        Sort-Object -Property ListItemText |
        ForEach-Object { $_ }
}
