#!/usr/bin/dotnet --
#:project ../../../source/timewarp-nuru/timewarp-nuru.csproj

// Test that interactive route execution works with NuruCoreAppHolder invoker
//
// NOTE: This test file has been disabled because it uses AddInteractiveRoute()
// which no longer exists. The source generator now automatically creates the
// --interactive,-i route when AddRepl() is called.

#if !JARIBU_MULTI
return await RunAllTests();
#endif

namespace TimeWarp.Nuru.Tests.ReplTests.InteractiveRouteExecution
{

[TestTag("REPL")]
public class InteractiveRouteExecutionTests
{
  [ModuleInitializer]
  internal static void Register() => RegisterTests<InteractiveRouteExecutionTests>();

  [Skip("AddInteractiveRoute API was removed; interactive routes are now generated by source generator when AddRepl() is used")]
  public static async Task Test_placeholder_for_skipped_class()
  {
    // This test class is skipped because AddInteractiveRoute() no longer exists.
    // The source generator automatically creates the --interactive,-i route
    // when AddRepl() is called. The session lifecycle tests (repl-01) now cover
    // interactive route execution.
    await Task.CompletedTask;
  }
}

} // namespace
