#!/usr/bin/dotnet --
#:project ../../../source/timewarp-nuru/timewarp-nuru.csproj

// Test AddInteractiveRoute uses alias syntax for single endpoint (Issue #119)
//
// NOTE: This test file has been disabled because it tests the old NuruAppBuilder
// runtime API (AddInteractiveRoute, EndpointCollection) which no longer exists.
// The new source generator architecture handles interactive routes automatically
// when AddRepl() is called - the generator emits the appropriate --interactive,-i route.
//
// The behavior being tested (alias syntax vs multiple endpoints) is now an
// implementation detail of the source generator, not runtime code.

#if !JARIBU_MULTI
return await RunAllTests();
#endif

namespace TimeWarp.Nuru.Tests.ReplTests.InteractiveRouteAlias
{

[TestTag("REPL")]
public class AddInteractiveRouteAliasTests
{
  [ModuleInitializer]
  internal static void Register() => RegisterTests<AddInteractiveRouteAliasTests>();

  [Skip("AddInteractiveRoute API was removed; interactive routes are now generated by source generator when AddRepl() is used")]
  public static async Task Test_placeholder_for_skipped_class()
  {
    // This test class is skipped because the AddInteractiveRoute API no longer exists.
    // The source generator now automatically creates the --interactive,-i route when
    // AddRepl() is called in the builder.
    await Task.CompletedTask;
  }
}

} // namespace TimeWarp.Nuru.Tests.ReplTests.InteractiveRouteAlias
