// System namespaces
// Microsoft namespaces
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using System;
global using System.Collections;
global using System.Globalization;
global using System.Reflection;
global using System.Text;
global using System.Text.Json;
global using static System.Console;
// TimeWarp namespaces
global using TimeWarp.Mediator;
global using TimeWarp.Nuru.CommandResolver;
global using TimeWarp.Nuru.Endpoints;
global using TimeWarp.Nuru.Help;
global using TimeWarp.Nuru.Parsing;
global using TimeWarp.Nuru.TypeConversion;
