// System namespaces
global using System.Diagnostics;
global using System.IO;
global using System.Net;
global using System.Text.RegularExpressions;
// Microsoft namespaces
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Logging.Abstractions;
global using Microsoft.Extensions.Options;
global using System;
global using System.Collections;
global using System.Globalization;
global using System.Reflection;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
// TimeWarp namespaces
global using TimeWarp.Mediator;
global using TimeWarp.Nuru.Parsing;