namespace TimeWarp.Nuru;

/// <summary>
/// Code generation methods for generating route registration code, route constants,
/// option calls, and alias registration.
/// </summary>
public partial class NuruAttributedRouteGenerator
{
  private static string GenerateRegistrationCode(List<AttributedRouteInfo> routes)
  {
    System.Text.StringBuilder sb = new();

    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("// Generated by TimeWarp.Nuru.Analyzers - NuruAttributedRouteGenerator");
    sb.AppendLine("// DO NOT EDIT");
    sb.AppendLine();
    sb.AppendLine("#nullable enable");
    sb.AppendLine();
    sb.AppendLine("namespace TimeWarp.Nuru.Generated;");
    sb.AppendLine();

    // Generate route constants
    sb.AppendLine("/// <summary>");
    sb.AppendLine("/// Generated compiled routes for attributed request classes.");
    sb.AppendLine("/// </summary>");
    sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"TimeWarp.Nuru.Analyzers\", \"1.0.0\")]");
    sb.AppendLine("internal static class GeneratedAttributedRoutes");
    sb.AppendLine("{");

    foreach (AttributedRouteInfo route in routes)
    {
      GenerateRouteConstant(sb, route);
      sb.AppendLine();

      // Generate separate compiled routes for each alias
      foreach (string alias in route.Aliases)
      {
        GenerateAliasRouteConstant(sb, route, alias);
        sb.AppendLine();
      }
    }

    sb.AppendLine("}");
    sb.AppendLine();

    // Generate module initializer
    sb.AppendLine("/// <summary>");
    sb.AppendLine("/// Module initializer that registers attributed routes with NuruRouteRegistry.");
    sb.AppendLine("/// </summary>");
    sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"TimeWarp.Nuru.Analyzers\", \"1.0.0\")]");
    sb.AppendLine("internal static class GeneratedAttributedRouteRegistration");
    sb.AppendLine("{");
    sb.AppendLine("  [global::System.Runtime.CompilerServices.ModuleInitializer]");
    sb.AppendLine("  internal static void Register()");
    sb.AppendLine("  {");

    foreach (AttributedRouteInfo route in routes)
    {
      GenerateRegistrationCall(sb, route);

      // Also register aliases
      foreach (string alias in route.Aliases)
      {
        GenerateAliasRegistrationCall(sb, route, alias);
      }
    }

    sb.AppendLine("  }");
    sb.AppendLine("}");

    return sb.ToString();
  }

  private static void GenerateRouteConstant(System.Text.StringBuilder sb, AttributedRouteInfo route)
  {
    string safeName = MakeSafeName(route.TypeName);

    sb.Append(CultureInfo.InvariantCulture, $"  internal static readonly global::TimeWarp.Nuru.CompiledRoute __Route_{safeName} = ");
    sb.AppendLine("new global::TimeWarp.Nuru.CompiledRouteBuilder()");

    // Add group prefix literals
    if (!string.IsNullOrEmpty(route.GroupPrefix))
    {
      foreach (string literal in route.GroupPrefix.Split(' ', StringSplitOptions.RemoveEmptyEntries))
      {
        sb.Append(CultureInfo.InvariantCulture, $"    .WithLiteral(\"{EscapeString(literal)}\")");
        sb.AppendLine();
      }
    }

    // Pattern should be a single literal (no spaces allowed - use [NuruRouteGroup] for multi-word routes)
    if (!string.IsNullOrEmpty(route.Pattern))
    {
      sb.Append(CultureInfo.InvariantCulture, $"    .WithLiteral(\"{EscapeString(route.Pattern)}\")");
      sb.AppendLine();
    }

    // Add parameters from [Parameter] attributes
    foreach (ParameterInfo param in route.Parameters)
    {
      if (param.IsCatchAll)
      {
        sb.Append(CultureInfo.InvariantCulture, $"    .WithCatchAll(\"{EscapeString(param.Name)}\"");
        if (param.TypeName is not null)
          sb.Append(CultureInfo.InvariantCulture, $", type: \"{param.TypeName}\"");
        if (param.Description is not null)
          sb.Append(CultureInfo.InvariantCulture, $", description: \"{EscapeString(param.Description)}\"");
        sb.AppendLine(")");
      }
      else
      {
        sb.Append(CultureInfo.InvariantCulture, $"    .WithParameter(\"{EscapeString(param.Name)}\"");
        if (param.TypeName is not null)
          sb.Append(CultureInfo.InvariantCulture, $", type: \"{param.TypeName}\"");
        if (param.Description is not null)
          sb.Append(CultureInfo.InvariantCulture, $", description: \"{EscapeString(param.Description)}\"");
        if (param.IsOptional)
          sb.Append(", isOptional: true");
        sb.AppendLine(")");
      }
    }

    // Add group options
    foreach (GroupOptionInfo opt in route.GroupOptions)
    {
      GenerateOptionCall(sb, opt.LongForm, opt.ShortForm, opt.PropertyName, opt.Description,
        opt.IsFlag, opt.IsValueOptional, false, opt.TypeName);
    }

    // Add options
    foreach (OptionInfo opt in route.Options)
    {
      GenerateOptionCall(sb, opt.LongForm, opt.ShortForm, opt.PropertyName, opt.Description,
        opt.IsFlag, opt.IsValueOptional, opt.IsRepeated, opt.TypeName);
    }

    // Add MessageType from inferred interfaces
    sb.Append(CultureInfo.InvariantCulture, $"    .WithMessageType(global::TimeWarp.Nuru.MessageType.{route.InferredMessageType})");
    sb.AppendLine();

    sb.AppendLine("    .Build();");

    // Generate pattern string for help display
    string patternString = BuildPatternString(route);
    sb.Append(CultureInfo.InvariantCulture, $"  internal const string __Pattern_{safeName} = \"{EscapeString(patternString)}\";");
    sb.AppendLine();
  }

  private static void GenerateOptionCall(System.Text.StringBuilder sb, string longForm, string? shortForm,
    string propertyName, string? description, bool isFlag, bool isValueOptional, bool isRepeated, string? typeName)
  {
    sb.Append(CultureInfo.InvariantCulture, $"    .WithOption(\"{EscapeString(longForm)}\"");

    if (shortForm is not null)
      sb.Append(CultureInfo.InvariantCulture, $", shortForm: \"{EscapeString(shortForm)}\"");

    if (!isFlag)
    {
      // Valued option
      sb.Append(CultureInfo.InvariantCulture, $", parameterName: \"{ToCamelCase(propertyName)}\"");
      sb.Append(", expectsValue: true");

      if (typeName is not null)
        sb.Append(CultureInfo.InvariantCulture, $", parameterType: \"{typeName}\"");

      if (isValueOptional)
        sb.Append(", parameterIsOptional: true");
    }

    if (description is not null)
      sb.Append(CultureInfo.InvariantCulture, $", description: \"{EscapeString(description)}\"");

    if (isRepeated)
      sb.Append(", isRepeated: true");

    // Make all options optional by default in attributed routes
    // (most CLI tools treat options as optional at runtime)
    sb.Append(", isOptionalFlag: true");

    sb.AppendLine(")");
  }

  private static void GenerateRegistrationCall(System.Text.StringBuilder sb, AttributedRouteInfo route)
  {
    string safeName = MakeSafeName(route.TypeName);
    string description = route.Description is not null ? $", \"{EscapeString(route.Description)}\"" : "";

    sb.Append(CultureInfo.InvariantCulture,
      $"    global::TimeWarp.Nuru.NuruRouteRegistry.Register(typeof({route.FullTypeName}), ");
    sb.Append(CultureInfo.InvariantCulture, $"GeneratedAttributedRoutes.__Route_{safeName}, ");
    sb.Append(CultureInfo.InvariantCulture, $"GeneratedAttributedRoutes.__Pattern_{safeName}");
    sb.Append(description);
    sb.AppendLine(");");
  }

  private static void GenerateAliasRegistrationCall(System.Text.StringBuilder sb, AttributedRouteInfo route, string alias)
  {
    string safeName = MakeSafeName(route.TypeName);
    string aliasSafeName = MakeSafeName(alias);
    string aliasPattern = BuildAliasPatternString(route, alias);
    string description = route.Description is not null ? $", \"{EscapeString(route.Description)}\"" : "";

    sb.Append(CultureInfo.InvariantCulture,
      $"    global::TimeWarp.Nuru.NuruRouteRegistry.Register(typeof({route.FullTypeName}), ");
    sb.Append(CultureInfo.InvariantCulture, $"GeneratedAttributedRoutes.__Route_{safeName}_Alias_{aliasSafeName}, ");
    sb.Append(CultureInfo.InvariantCulture, $"\"{EscapeString(aliasPattern)}\"");
    sb.Append(description);
    sb.AppendLine(");");
  }

  private static void GenerateAliasRouteConstant(System.Text.StringBuilder sb, AttributedRouteInfo route, string alias)
  {
    string safeName = MakeSafeName(route.TypeName);
    string aliasSafeName = MakeSafeName(alias);

    sb.Append(CultureInfo.InvariantCulture, $"  internal static readonly global::TimeWarp.Nuru.CompiledRoute __Route_{safeName}_Alias_{aliasSafeName} = ");
    sb.AppendLine("new global::TimeWarp.Nuru.CompiledRouteBuilder()");

    // Add group prefix literals (same as main route)
    if (!string.IsNullOrEmpty(route.GroupPrefix))
    {
      foreach (string literal in route.GroupPrefix.Split(' ', StringSplitOptions.RemoveEmptyEntries))
      {
        sb.Append(CultureInfo.InvariantCulture, $"    .WithLiteral(\"{EscapeString(literal)}\")");
        sb.AppendLine();
      }
    }

    // Alias should be a single literal (no spaces allowed)
    if (!string.IsNullOrEmpty(alias))
    {
      sb.Append(CultureInfo.InvariantCulture, $"    .WithLiteral(\"{EscapeString(alias)}\")");
      sb.AppendLine();
    }

    // Add parameters from [Parameter] attributes (same as main route)
    foreach (ParameterInfo param in route.Parameters)
    {
      if (param.IsCatchAll)
      {
        sb.Append(CultureInfo.InvariantCulture, $"    .WithCatchAll(\"{EscapeString(param.Name)}\"");
        if (param.TypeName is not null)
          sb.Append(CultureInfo.InvariantCulture, $", type: \"{param.TypeName}\"");
        if (param.Description is not null)
          sb.Append(CultureInfo.InvariantCulture, $", description: \"{EscapeString(param.Description)}\"");
        sb.AppendLine(")");
      }
      else
      {
        sb.Append(CultureInfo.InvariantCulture, $"    .WithParameter(\"{EscapeString(param.Name)}\"");
        if (param.TypeName is not null)
          sb.Append(CultureInfo.InvariantCulture, $", type: \"{param.TypeName}\"");
        if (param.Description is not null)
          sb.Append(CultureInfo.InvariantCulture, $", description: \"{EscapeString(param.Description)}\"");
        if (param.IsOptional)
          sb.Append(", isOptional: true");
        sb.AppendLine(")");
      }
    }

    // Add group options (same as main route)
    foreach (GroupOptionInfo opt in route.GroupOptions)
    {
      GenerateOptionCall(sb, opt.LongForm, opt.ShortForm, opt.PropertyName, opt.Description,
        opt.IsFlag, opt.IsValueOptional, false, opt.TypeName);
    }

    // Add options (same as main route)
    foreach (OptionInfo opt in route.Options)
    {
      GenerateOptionCall(sb, opt.LongForm, opt.ShortForm, opt.PropertyName, opt.Description,
        opt.IsFlag, opt.IsValueOptional, opt.IsRepeated, opt.TypeName);
    }

    // Add MessageType from inferred interfaces (same as main route)
    sb.Append(CultureInfo.InvariantCulture, $"    .WithMessageType(global::TimeWarp.Nuru.MessageType.{route.InferredMessageType})");
    sb.AppendLine();

    sb.AppendLine("    .Build();");
  }
}
